Implement simple keyboard controller
robinlinden/desunes pull request #10
Opened 2021-10-30 09:55 UTC by sa12123

2021-10-31 17:43 UTC, robinlinden requested changes

2021-10-31 17:43 UTC, robinlinden commented on application/src/keyboard_controller.cpp
> +    if (key_button_map_.find(key_id) != key_button_map_.end()) {
This could be done using the (new in C++17) if-init construction to avoid looking up the key_id twice.

Something like...
```
if (auto key = key_button_map_.find(key_id); key != key_button_map_.end()) {
  controller_.set(*key, is_down);
}
```

2021-11-02 00:17 UTC, sa12123 commented on application/src/keyboard_controller.cpp
> +    if (key_button_map_.find(key_id) != key_button_map_.end()) {
Nice feature! Fixed!

2021-11-03 22:53 UTC, robinlinden approved these changes
Looks good!

2021-11-03 22:54 UTC, merged